# Generated by Django 2.0.13 on 2019-04-11 15:43

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0005_auto_20190410_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('to_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('body', models.CharField(max_length=160)),
                ('from_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_parent', to='students.Parent')),
                ('to_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_parent', to='students.Parent')),
            ],
        ),
    ]
