# Generated by Django 2.0.13 on 2019-04-12 06:51

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0006_auto_20190411_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('sid', models.CharField(max_length=34, primary_key=True, serialize=False)),
                ('from_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('to_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('body', models.CharField(max_length=160)),
                ('from_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_parent', to='students.Parent')),
                ('to_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_parent', to='students.Parent')),
            ],
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=12, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.Message')),
            ],
        ),
    ]
