# Generated by Django 2.0.13 on 2019-04-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagestatus',
            name='message',
        ),
        migrations.AddField(
            model_name='messagestatus',
            name='sid',
            field=models.CharField(default='', max_length=34),
            preserve_default=False,
        ),
    ]
