# Generated by Django 2.0.13 on 2019-04-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='raw_body',
        ),
        migrations.AddField(
            model_name='message',
            name='clean_body',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='sid',
            field=models.CharField(max_length=34, null=True),
        ),
    ]
