# Generated by Django 2.0.13 on 2019-04-13 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20190412_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='from_parent',
        ),
        migrations.RemoveField(
            model_name='message',
            name='to_parent',
        ),
    ]
