# Generated by Django 2.0.13 on 2019-04-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20190411_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='raw_body',
            field=models.CharField(max_length=160, null=True),
        ),
    ]
