# Generated by Django 2.0.13 on 2019-04-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_auto_20190411_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='clean_body',
        ),
        migrations.RemoveField(
            model_name='message',
            name='raw_body',
        ),
        migrations.AddField(
            model_name='message',
            name='body',
            field=models.CharField(default='', max_length=160),
            preserve_default=False,
        ),
    ]
