# Generated by Django 2.0.13 on 2019-04-20 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_auto_20190419_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
