# Generated by Django 2.0.13 on 2019-04-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed',
            field=models.BooleanField(default=False),
        ),
    ]
