# Generated by Django 2.0.13 on 2019-04-15 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='allowed',
        ),
    ]
