# Generated by Django 2.0.13 on 2019-04-08 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['first_name', 'last_name', 'birth_date']},
        ),
    ]
