# Generated by Django 2.0.13 on 2019-04-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20190407_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(to='students.Parent'),
        ),
    ]
