# Generated by Django 2.0.13 on 2019-04-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20190410_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parents',
        ),
        migrations.AddField(
            model_name='parent',
            name='students',
            field=models.ManyToManyField(to='students.Student'),
        ),
    ]
