# Generated by Django 2.0.13 on 2019-10-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20191021_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='classroom',
            new_name='classrooms',
        ),
        migrations.AlterField(
            model_name='student',
            name='classrooms',
            field=models.ManyToManyField(to='students.Classroom'),
        ),
    ]
